apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: prod
resources:
  - ../../base
patches:
  - path: replica_count.yaml
  #   target:
  #     namespace: default
  - path: cpu_count.yaml
  #   target:
  #     namespace: default
